sudo: required
addons:
  apt:
    update: true
    packages:
      - docker-ce
services:
  - docker
script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - source utils.sh
  - alpine_arm_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm")
  - echo $alpine_arm_sha
  - alpine_amd64_sha=$(get_manifest_sha "treehouses/alpine:latest" "amd64")
  - echo $alpine_amd64_sha
  - alpine_arm64_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm64")
  - echo $alpine_arm64_sha
  - novnc_arm_sha=$(get_manifest_sha "treehouses/novnc:latest" "arm")
  - echo $novnc_arm_sha
  - novnc_amd64_sha=$(get_manifest_sha "treehouses/novnc" "amd64")
  - echo $novnc_amd64_sha
  - novnc_arm64_sha=$(get_manifest_sha "treehouses/novnc" "arm64")
  - echo $novnc_arm64_sha
  - flag_arm=$(is_base "treehouses/alpine@"$alpine_arm_sha "treehouses/novnc@"$novnc_arm_sha )
  - echo $flag_arm
  - flag_amd64=$(is_base "treehouses/alpine@"$alpine_amd64_sha "treehouses/novnc@"$novnc_amd64_sha )
  - echo $flag_amd64
  - flag_arm64=$(is_base "treehouses/alpine@"$alpine_arm64_sha "treehouses/novnc@"$novnc_arm64_sha )
  - echo $flag_arm64
  - echo $DOCKERAPIKEY | docker login -u "sevenseas" --password-stdin
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - build_image "treehouses/alpine:latest" arm "treehouses/novnc"
  - build_image "treehouses/alpine:latest" arm64 "treehouses/novnc"
  - build_image "treehouses/alpine:latest" amd64 "treehouses/novnc"
  - flag=$(compare "treehouses/alpine@"$alpine_arm_sha "treehouses/novnc@"$novnc_arm_sha "treehouses/alpine@"$alpine_amd64_sha "treehouses/novnc@"$novnc_amd64_sha  "treehouses/alpine@"$alpine_arm64_sha "treehouses/novnc@"$novnc_arm64_sha)
  - echo $flag
before_deploy:
  - deploy_image "treehouses/novnc" arm
  - deploy_image "treehouses/novnc" arm64
  - deploy_image "treehouses/novnc" amd64
  - tag_time=$(date +%Y%m%d%H%M)
  - echo $tag_time
  - tag_latest="latest"
  - create_manifest treehouses/novnc $tag_latest $tag_time treehouses/novnc-tags:arm treehouses/novnc-tags:arm64 treehouses/novnc-tags:amd64
  - docker manifest inspect treehouses/novnc:$tag_latest
  - docker manifest inspect treehouses/novnc:$tag_time
deploy:
  - provider: script
    script: docker manifest push treehouses/novnc:$tag_latest; docker manifest push treehouses/novnc:$tag_time
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$flag = true"
env:
  global:
    secure: "Vjr9ELEksYDZ8Ma2rgvUoLwVby6tZM/P2ohOIOfpscclqto8Aj3ziLKBV8Xb6cO7rWjrSMK7kuUcXqTFjC3MQpGuJWDE2zAUkyo6666W+G6vJvIaLm3KTfhvArs0QNHaC8eQgpYFQDl3sqwjgLPB/UyFHJuswxiM4x9wfTb71yDiWCBZS5j3noDwA62R34+MvasulpHplaI1zSxAo2es+4b1HF+lWjaliFiPWkUXF5+T7JusJInlac2fAKxnzj9KsWO9XFKof14thhfuw0toAcfYIAm+rzveKLaX/Ziojb4fMpqg687C4IxRsxxpOrZd21CmaIbf7jcz0YJFXDIxgT9YkpLcDJpKncX9YYZQ5p4aE3MNlvgLKG/YyipE+JahFd5pZrayGzIyyjWGMlRoov5fJ8G6BdteDVegYRV09GGqpGN6qrNBXVDz2POv8ABp777YqbJ23IsGrhLgKfhhFRjWXJ2VJ0vaet3PB+fhZg6yVaMGiWKq2hhesuDeL1xn28Ot6jaMZ7vTbpSdZ5ug3UVPkjRhpCpaY1eZKBXZKMBrcoZKNU35d9VZYrVU0G9g9QQSN+1SpwSmBCeIGeeEu5J6zGMybtaLdcNSFQCYZhePVcAnyrsgC1Xp95O+npccFZD4U0ukqhCDUzZ5IQBbsSRiwWk4nj7667j2dXkiBdQ="
